version: '3.9'

services:
  web:
    image: httpd:latest
    container_name: my-apache
    volumes:
      - /data/apache:/usr/local/apache2/htdocs
    ports:
      - "80:80"
    networks:
      - minha-rede

networks: 
  minha-rede:
    driver: bridge


